""" FASTA SEQUENCE USED TO CALCULATE TO MOLECULAR WEIGHT OF THE PROTEIN """
PROTEIN_SEQUENCE = ("MADPAAGPPPSEGEESTVRFARKGALRQKNVHEVKNHKFTARFFKQPT\n"
                    "FCSHCTDFIWGFGKQGFQCQVCCFVVHKRCHEFVTFSCPGADKGPASD\n"
                    "DPRSKHKFKIHTYSSPTFCDHCGSLLYGLIHQGMKCDTCMMNVHKRCV\n"
                    "MNVPSLCGTDHTERRGRIYIQAHIDREVLIVVVRDAKNLVPMDPNGLS\n"
                    "DPYVKLKLIPDPKSESKQKTKTIKCSLNPEWNETFRFQLKESDKDRRL\n"
                    "SVEIWDWDLTSRNDFMGSLSFGISELQKAGVDGWFKLLSQEEGEYFNV\n"
                    "PVPPEGSEGNEELRQKFERAKIGQGTKAPEEKTANTISKFDNNGNRDR\n"
                    "MKLTDFNFLMVLGKGSFGKVMLSERKGTDELYAVKILKKDVVIQDDDV\n"
                    "ECTMVEKRVLALPGKPPFLTQLHSCFQTMDRLYFVMEYVNGGDLMYHI\n"
                    "QQVGRFKEPHAVFYAAEIAIGLFFLQSKGIIYRDLKLDNVMLDSEGHI\n"
                    "KIADFGMCKENIWDGVTTKTFCGTPDYIAPEIIAYQPYGKSVDWWAFG\n"
                    "VLLYEMLAGQAPFEGEDEDELFQSIMEHNVAYPKSMSKEAVAICKGLM\n"
                    "TKHPGKRLGCGPEGERDIKEHAFFRYIDWEKLERKEIQPPYKPKARDK\n"
                    "RDTSNFDKEFTRQPVELTPTDKLFIMNLDQNEFAGFSYTNPEFVINV")

# Average molecular weight per amino acid in daltons:
AVERAGE_MOLECULAR_WEIGHT = 110

# to get rid of newline characters
PROTEIN_SEQUENCE = PROTEIN_SEQUENCE.replace('\r', '').replace('\n', '')

# Length of the protein sequence:
LENGTH_PROTEIN = len(PROTEIN_SEQUENCE)

# Calculation of molecular weight of the protein sequence:
MOLECULAR_WEIGHT = LENGTH_PROTEIN * AVERAGE_MOLECULAR_WEIGHT

# Converting molecular weight from daltons to kilodaltons:
MOL_WEIGHT_KILODALTONS = MOLECULAR_WEIGHT / 1000

# Outputing the result:
print('The length of "Protein kinase C beta type" is: ' + str(LENGTH_PROTEIN))
print\
    ('The average weight of this protein sequence in kilodaltons is:' + str(MOL_WEIGHT_KILODALTONS))
